# Site settings
title: migration.fm
description: "日夜Salesforceと格闘しながらサービスを開発しているエンジニアが話す Salesforce Developer 向けのPodcastです。"
subtitle: "Salesforce Developer 向け Podcast migration.fm #migrationfm"
squareLogo: "https://i1.sndcdn.com/avatars-000223269201-7h2ox0-original.jpg"
managerName: migration.fm
managerEmail: migrationfm@gmail.com
copyright: "&#x2117; &amp; &#xA9; 2016"
keywords: Salesforce, Podcast
baseurl: "/"
url: "http://migration.fm"
lang: ja
timezone: JPN

# Build settings
markdown: kramdown
paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"
permalink: "/:title/"
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# author info
# add your appropriate info here
author: Akira.Kuratani
bio: Salesforce Developer at TeamSpirit Inc.
email: migrationfm@gmail.com
email_md5: 0f5a90aa72eccd0071a7dae1187dac9f # md5 hash of your email
twitter_username: migrationfm
twitter_hashtag: migrationfm
github_username: kuratani
facebook_pagename: migration.fm
rss_url: http://migration.fm/feed.xml
itunes_url: https://itunes.apple.com/jp/podcast/migration.fm/id1111956465
andriod_url: https://www.subscribeonandroid.com/migration.fm/feed.xml
blog_url: https://blog.migration.fm/

# theme: minima
theme_color: blue-pink # deep_purple-pink
